apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: breakfast-service-autoscaler
  namespace: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: breakfast-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
